apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: django-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image:  gobikrishnan/my-docker-app  # Replace with your actual image name
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "True"  # Change to "False" in production
